//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clubes
    {
        public int IdClube { get; set; }
        public string Nome { get; set; }
        public string SiglaEstado { get; set; }
        public string Serie { get; set; }
        public string CaminhoBandeira { get; set; }
    }
}
