//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PalpitecoEntities : DbContext
    {
        public PalpitecoEntities()
            : base("name=PalpitecoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campeonatos> Campeonatos { get; set; }
        public virtual DbSet<Clubes> Clubes { get; set; }
        public virtual DbSet<Jogadores> Jogadores { get; set; }
        public virtual DbSet<JogadorXPalpite> JogadorXPalpite { get; set; }
        public virtual DbSet<Jogos> Jogos { get; set; }
        public virtual DbSet<Palpites> Palpites { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Rodadas> Rodadas { get; set; }
    }
}
