//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jogos()
        {
            this.Palpites = new HashSet<Palpites>();
        }
    
        public int IdJogo { get; set; }
        public Nullable<int> TimeCasa { get; set; }
        public Nullable<int> GolCasa { get; set; }
        public Nullable<int> TimeVisitante { get; set; }
        public Nullable<int> GolVisitante { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public int IdRodada { get; set; }
    
        public virtual Rodadas Rodadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Palpites> Palpites { get; set; }
    }
}
