//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palpites
    {
        public int IdPalpite { get; set; }
        public string TimeCasa { get; set; }
        public int GolCasa { get; set; }
        public string TimeVisitante { get; set; }
        public int GolVisitante { get; set; }
        public int PontosFeitos { get; set; }
        public System.DateTime Data { get; set; }
        public int IdRodada { get; set; }
        public int IdJogo { get; set; }
        public int IdJogador { get; set; }
    
        public virtual Jogadores Jogadores { get; set; }
        public virtual Jogos Jogos { get; set; }
        public virtual Rodadas Rodadas { get; set; }
    }
}
